version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
    overwrite: yes
    permissions:
      - object: /home/ec2-user/app/scripts
        pattern: "*.sh"
        owner: ec2-user
        group: ec2-user
        mode: 755

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user