version: "3.9"
services:
  database:
    image: mariadb:latest
    container_name: mariadb_local
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hello-app
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_local
    ports:
      - "6379:6379"
    command: redis-server --requirepass root
    environment:
      REDIS_PASSWORD: root
    volumes:
      - redis_data:/data
    networks:
      - app_network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hello_app_local
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_TYPE: mariadb
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: hello-app
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: root
    depends_on:
      - database
      - redis
    networks:
      - app_network
volumes:
  db_data:
  redis_data:
networks:
  app_network: